import { StyleSheet, View, ScrollView, TouchableOpacity, Text, Image} from 'react-native'
import React, { useContext, useEffect } from 'react'
import SearchBar from '../components/SearchBar'
import Categories from '../components/Categories'
import { StoreContext } from '../context.js/store-context'
import Ilanlar from '../components/Ilanlar'

const categories = [
  {
      name : 'Emlak',
      icon : 'home',
      bg : '#f6af18',
      to : 'IlanPageTwo',
      description : 'deneme',
      altCate : [
          {name : 'Konut',
          to : 'IlanPageTwo',
          altCate : [
              {name : 'Satılık',
              to : 'IlanPageTwo',
              altCate : [
                  {to : 'ListIlan' ,name : 'Daire'},
                  {to : 'ListIlan' ,name : 'Rezidans'},
                  {to : 'ListIlan' ,name : 'Müstakil Ev'},
                  {to : 'ListIlan' ,name : 'Villa'},
                  {to : 'ListIlan' ,name : 'Çiftlik Evi'},
                  {to : 'ListIlan' ,name : 'Köşk & Konak'},
                  {to : 'ListIlan' ,name : 'Yalı'},
                  {to : 'ListIlan' ,name : 'Yalı Dairesi'},
                  {to : 'ListIlan' ,name : 'Yazlık'},
                  {to : 'ListIlan' ,name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              to : 'IlanPageTwo',
              altCate : [
                  { to : 'ListIlan' ,name : 'Daire'},
                  { to : 'ListIlan' ,name : 'Rezidans'},
                  { to : 'ListIlan' ,name : 'Müstakil Ev'},
                  { to : 'ListIlan' ,name : 'Villa'},
                  { to : 'ListIlan' ,name : 'Çiftlik Evi'},
                  { to : 'ListIlan' ,name : 'Köşk & Konak'},
                  { to : 'ListIlan' ,name : 'Yalı'},
                  { to : 'ListIlan' ,name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              to : 'IlanPageTwo',
              altCate : [
                  { to : 'ListIlan' ,name : 'Daire'},
                  { to : 'ListIlan' ,name : 'Rezidans'},
                  { to : 'ListIlan' ,name : 'Müstakil Ev'},
                  { to : 'ListIlan' ,name : 'Villa'},
                  { to : 'ListIlan' ,name : 'Devre Mülk'},
                  { to : 'ListIlan' ,name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              to : 'IlanPageTwo',
              altCate : [
                  {to : 'ListIlan' ,name : 'Daire'},
                  {to : 'ListIlan' ,name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          to : 'IlanPageTwo',
          altCate : [
              {name : 'Satılık',
              to : 'IlanPageTwo',
              altCate : [
                  {to : 'ListIlan' , name : 'Akaryakıt İstasyonu'},
                  {to : 'ListIlan' , name : 'Apartman Dairesi'},
                  {to : 'ListIlan' , name : 'Atölye'},
                  {to : 'ListIlan' , name : 'AVM'},
                  {to : 'ListIlan' , name : 'Büfe'},
                  {to : 'ListIlan' , name : 'Büro & Ofis'},
                  {to : 'ListIlan' , name : 'Cafe & Bar'},
                  {to : 'ListIlan' , name : 'Çiftlik'},
                  {to : 'ListIlan' , name : 'Depo & Antrepo'},
                  {to : 'ListIlan' , name : 'Düğün Salonu'},
                  {to : 'ListIlan' , name : 'Dükkan & Mağaza'},
                  {to : 'ListIlan' , name : 'Enerji Santrali'},
                  {to : 'ListIlan' , name : 'Fabrika'},
                  {to : 'ListIlan' , name : 'Garaj & Park Yeri'},
                  {to : 'ListIlan' , name : 'İmalathane'},
                  {to : 'ListIlan' , name : 'İş Hanı Katı & Ofisi'},
                  {to : 'ListIlan' , name : 'Kantin'},
                  {to : 'ListIlan' , name : 'Kır & Kahvaltı Bahçesi'},
                  {to : 'ListIlan' , name : 'Kıraathane'},
                  {to : 'ListIlan' , name : 'Komple Bina'},
                  {to : 'ListIlan' , name : 'Madem Ocağı'},
                  {to : 'ListIlan' , name : 'Otopark'},
                  {to : 'ListIlan' , name : 'Pastane & Fırın'},
                  {to : 'ListIlan' , name : 'Pazar Yeri'},
                  {to : 'ListIlan' , name : 'Plaza'},
                  {to : 'ListIlan' , name : 'Plaza Katı'},
                  {to : 'ListIlan' , name : 'Radyo İstasyonu'},
                  {to : 'ListIlan' , name : 'Restoran & Lokanta'},
                  {to : 'ListIlan' , name : 'Rezidans Katı & Ofisi'},
                  {to : 'ListIlan' , name : 'Sağlık Merkezi'},
                  {to : 'ListIlan' , name : 'Sinema & Konferans Salonu'},
                  {to : 'ListIlan' , name : 'SPA, Hamam & Sauna'},
                  {to : 'ListIlan' , name : 'Spor Tesisi'},
                  {to : 'ListIlan' , name : 'Villa'},
                  {to : 'ListIlan' , name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              to : 'IlanPageTwo',
              altCate : [
                  {to : 'ListIlan' ,name : 'Akaryakıt İstasyonu'},
                  {to : 'ListIlan' ,name : 'Apartman Dairesi'},
                  {to : 'ListIlan' ,name : 'Atölye'},
                  {to : 'ListIlan' ,name : 'AVM'},
                  {to : 'ListIlan' ,name : 'Büfe'},
                  {to : 'ListIlan' ,name : 'Büro & Ofis'},
                  {to : 'ListIlan' ,name : 'Cafe & Bar'},
                  {to : 'ListIlan' ,name : 'Çiftlik'},
                  {to : 'ListIlan' ,name : 'Depo & Antrepo'},
                  {to : 'ListIlan' ,name : 'Düğün Salonu'},
                  {to : 'ListIlan' ,name : 'Dükkan & Mağaza'},
                  {to : 'ListIlan' ,name : 'Enerji Santrali'},
                  {to : 'ListIlan' ,name : 'Fabrika'},
                  {to : 'ListIlan' ,name : 'Garaj & Park Yeri'},
                  {to : 'ListIlan' ,name : 'İmalathane'},
                  {to : 'ListIlan' ,name : 'İş Hanı Katı & Ofisi'},
                  {to : 'ListIlan' ,name : 'Kantin'},
                  {to : 'ListIlan' ,name : 'Kır & Kahvaltı Bahçesi'},
                  {to : 'ListIlan' ,name : 'Kıraathane'},
                  {to : 'ListIlan' ,name : 'Komple Bina'},
                  {to : 'ListIlan' ,name : 'Madem Ocağı'},
                  {to : 'ListIlan' ,name : 'Otopark'},
                  {to : 'ListIlan' ,name : 'Pastane & Fırın'},
                  {to : 'ListIlan' ,name : 'Pazar Yeri'},
                  {to : 'ListIlan' ,name : 'Plaza'},
                  {to : 'ListIlan' ,name : 'Plaza Katı'},
                  {to : 'ListIlan' ,name : 'Radyo İstasyonu'},
                  {to : 'ListIlan' ,name : 'Restoran & Lokanta'},
                  {to : 'ListIlan' ,name : 'Rezidans Katı & Ofisi'},
                  {to : 'ListIlan' ,name : 'Sağlık Merkezi'},
                  {to : 'ListIlan' ,name : 'Sinema & Konferans Salonu'},
                  {to : 'ListIlan' ,name : 'SPA, Hamam & Sauna'},
                  {to : 'ListIlan' ,name : 'Spor Tesisi'},
                  {to : 'ListIlan' ,name : 'Villa'},
                  {to : 'ListIlan' ,name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              to : 'IlanPageTwo',
              altCate : [
                  {to : 'ListIlan' ,name : 'Acente'},
                  {to : 'ListIlan' ,name : 'Akaryakıt İstasyonu'},
                  {to : 'ListIlan' ,name : 'Aktar & Baharatçı'},
                  {to : 'ListIlan' ,name : 'Anaokulu & Kreş'},
                  {to : 'ListIlan' ,name : 'Apartman Dairesi'},
                  {to : 'ListIlan' ,name : 'Araç Showroom & Servis'},
                  {to : 'ListIlan' ,name : 'Atölye'},
                  {to : 'ListIlan' ,name : 'AVM Standı'},
                  {to : 'ListIlan' ,name : 'Balıkçı'},
                  {to : 'ListIlan' ,name : 'Bar'},
                  {to : 'ListIlan' ,name : 'Bijuteri'},
                  {to : 'ListIlan' ,name : 'Börekçi'},
                  {to : 'ListIlan' ,name : 'Büfe'},
                  {to : 'ListIlan' ,name : 'Büro & Ofis'},
                  {to : 'ListIlan' ,name : 'Cafe'},
                  {to : 'ListIlan' ,name : 'CD & DVD Dükkanı'},
                  {to : 'ListIlan' ,name : 'Cep Telefonu Dükkanı'},
                  {to : 'ListIlan' ,name : 'Çamaşırhane'},
                  {to : 'ListIlan' ,name : 'Çay Ocağı'},
                  {to : 'ListIlan' ,name : 'Çiçekçi & Fidanlık'},
                  {to : 'ListIlan' ,name : 'Çiftlik'},
                  {to : 'ListIlan' ,name : 'Depo & Antrepo'},
                  {to : 'ListIlan' ,name : 'Düğün Salonu'},
                  {to : 'ListIlan' ,name : 'Dükkan & Mağaza'},
                  {to : 'ListIlan' ,name : 'Eczane & Medikal'},
                  {to : 'ListIlan' ,name : 'Elektrikçi & Hırdavatçı'},
                  {to : 'ListIlan' ,name : 'Elektronik Mağazası'},
                  {to : 'ListIlan' ,name : 'Etkinlik & Performans Salonu'},
                  {to : 'ListIlan' ,name : 'Fabrika & Ürem Tesisi'},
                  {to : 'ListIlan' ,name : 'Fatura Merkezi'},
                  {to : 'ListIlan' ,name : 'Fotoğraf Stüdyosu'},
                  {to : 'ListIlan' ,name : 'Gece Kulübü & Disko'},
                  {to : 'ListIlan' ,name : 'Giyim Mağazası'},
                  {to : 'ListIlan' ,name : 'Gözlükçü'},
                  {to : 'ListIlan' ,name : 'Halı Yıkama'},
                  {to : 'ListIlan' ,name : 'Huzur Evi'},
                  {to : 'ListIlan' ,name : 'İmalathane'},
                  {to : 'ListIlan' ,name : 'İnternet & Oyun Cafe'},
                  {to : 'ListIlan' ,name : 'İş Hanı'},
                  {to : 'ListIlan' ,name : 'İş Hanı Katı & Ofisi'},
                  {to : 'ListIlan' ,name : 'Kantin'},
                  {to : 'ListIlan' ,name : 'Kasap'},
                  {to : 'ListIlan' ,name : 'Kır & Kahvaltı Bahçesi'},
                  {to : 'ListIlan' ,name : 'Kıraathane'},
                  {to : 'ListIlan' ,name : 'Kırtasiye'},
                  {to : 'ListIlan' ,name : 'Kozmetik Mağazası'},
                  {to : 'ListIlan' ,name : 'Kuaför & Güzellik Merkezi'},
                  {to : 'ListIlan' ,name : 'Kurs & Eğitim Merkezi'},
                  {to : 'ListIlan' ,name : 'Kuru Temizleme'},
                  {to : 'ListIlan' ,name : 'Kuruyemişçi'},
                  {to : 'ListIlan' ,name : 'Kuyumcu'},
                  {to : 'ListIlan' ,name : 'Lunapark'},
                  {to : 'ListIlan' ,name : 'Maden Ocağı'},
                  {to : 'ListIlan' ,name : 'Manav'},
                  {to : 'ListIlan' ,name : 'Market'},
                  {to : 'ListIlan' ,name : 'Matbaa'},
                  {to : 'ListIlan' ,name : 'Modaevi'},
                  {to : 'ListIlan' ,name : 'Muayenehane'},
                  {to : 'ListIlan' ,name : 'Nakliyat & Kargo'},
                  {to : 'ListIlan' ,name : 'Nalbur'},
                  {to : 'ListIlan' ,name : 'Okul'},
                  {to : 'ListIlan' ,name : 'Otopark / Garaj'},
                  {to : 'ListIlan' ,name : 'Oto Servis & Bakım'},
                  {to : 'ListIlan' ,name : 'Pastane & Fırın'},
                  {to : 'ListIlan' ,name : 'Pazar Yeri'},
                  {to : 'ListIlan' ,name : 'Plaza'},
                  {to : 'ListIlan' ,name : 'Plaza Katı'},
                  {to : 'ListIlan' ,name : 'Radyo İstasyonu'},
                  {to : 'ListIlan' ,name : 'Restoran & Lokanta'},
                  {to : 'ListIlan' ,name : 'Rezidans Katı & Ofisi'},
                  {to : 'ListIlan' ,name : 'Sağlık Merkezi'},
                  {to : 'ListIlan' ,name : 'Sinema & Konferans Salonu'},
                  {to : 'ListIlan' ,name : 'SPA, Hamam & Sauna'},
                  {to : 'ListIlan' ,name : 'Spor Tesisi'},
                  {to : 'ListIlan' ,name : 'Villa'},
                  {to : 'ListIlan' ,name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık',
              to : 'IlanPageTwo',
              altCate : []
              }
          ]
          },
          {name : 'Arsa',
          to : 'IlanPageTwo',
          altCate: [
              {to : 'ListIlan' ,name : 'Satılık'},
              {to : 'ListIlan' ,name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          to : 'IlanPageTwo',
          altCate: [
              {to : 'ListIlan' ,name : 'Satılık'},
              {to : 'ListIlan' ,name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          to : 'IlanPageTwo',
          altCate: [
              {to : 'ListIlan' ,name : 'Akdeniz Bölgesi'},
              {to : 'ListIlan' ,name : 'Doğu Anadolu Bölgesi'},
              {to : 'ListIlan' ,name : 'Ege Bölgesi'},
              {to : 'ListIlan' ,name : 'Güneydoğu Anadolu Bölgesi'},
              {to : 'ListIlan' ,name : 'İç Anadolu Bölgesi'},
              {to : 'ListIlan' ,name : 'Karadeniz Bölgesi'},
              {to : 'ListIlan' ,name : 'Marmara Bölgesi'},
              {to : 'ListIlan' ,name : 'Kıbrıs'},
              {to : 'ListIlan' ,name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis',
          to : 'IlanPageTwo',
          altCate : []
          },
      ]
  },
  {
      name : 'Vasıta',
      to : 'IlanPageTwo',
      icon : 'directions-car',
      description : 'deneme',
      bg : '#f1282c',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
  {
      name : 'Yedek Parça vs.',
      to : 'IlanPageTwo',
      icon : 'build',
      description : 'deneme',
      bg : '#05b6bb',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {to : 'ListIlan' ,name : 'Akaryakıt İstasyonu'},
                  {to : 'ListIlan' ,name : 'Apartman Dairesi'},
                  {to : 'ListIlan' ,name : 'Atölye'},
                  {to : 'ListIlan' ,name : 'AVM'},
                  {to : 'ListIlan' ,name : 'Büfe'},
                  {to : 'ListIlan' ,name : 'Büro & Ofis'},
                  {to : 'ListIlan' ,name : 'Cafe & Bar'},
                  {to : 'ListIlan' ,name : 'Çiftlik'},
                  {to : 'ListIlan' ,name : 'Depo & Antrepo'},
                  {to : 'ListIlan' ,name : 'Düğün Salonu'},
                  {to : 'ListIlan' ,name : 'Dükkan & Mağaza'},
                  {to : 'ListIlan' ,name : 'Enerji Santrali'},
                  {to : 'ListIlan' ,name : 'Fabrika'},
                  {to : 'ListIlan' ,name : 'Garaj & Park Yeri'},
                  {to : 'ListIlan' ,name : 'İmalathane'},
                  {to : 'ListIlan' ,name : 'İş Hanı Katı & Ofisi'},
                  {to : 'ListIlan' ,name : 'Kantin'},
                  {to : 'ListIlan' ,name : 'Kır & Kahvaltı Bahçesi'},
                  {to : 'ListIlan' ,name : 'Kıraathane'},
                  {to : 'ListIlan' ,name : 'Komple Bina'},
                  {to : 'ListIlan' ,name : 'Madem Ocağı'},
                  {to : 'ListIlan' ,name : 'Otopark'},
                  {to : 'ListIlan' ,name : 'Pastane & Fırın'},
                  {to : 'ListIlan' ,name : 'Pazar Yeri'},
                  {to : 'ListIlan' ,name : 'Plaza'},
                  {to : 'ListIlan' ,name : 'Plaza Katı'},
                  {to : 'ListIlan' ,name : 'Radyo İstasyonu'},
                  {to : 'ListIlan' ,name : 'Restoran & Lokanta'},
                  {to : 'ListIlan' ,name : 'Rezidans Katı & Ofisi'},
                  {to : 'ListIlan' ,name : 'Sağlık Merkezi'},
                  {to : 'ListIlan' ,name : 'Sinema & Konferans Salonu'},
                  {to : 'ListIlan' ,name : 'SPA, Hamam & Sauna'},
                  {to : 'ListIlan' ,name : 'Spor Tesisi'},
                  {to : 'ListIlan' ,name : 'Villa'},
                  {to : 'ListIlan' ,name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
  {
      name : 'İkinci El ve Sıfır Alışveriş',
      to : 'IlanPageTwo',
      icon : 'shopping-cart',
      description : 'deneme',
      bg : '#6d71f6',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
  {
      name : 'İş Makineleri ve Sanayi',
      to : 'IlanPageTwo',
      icon : 'agriculture',
      description : 'deneme',
      bg : '#a861fe',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
  {
      name : 'Özel Ders Verenler',
      to : 'IlanPageTwo',
      icon : 'menu-book',
      bg : '#52ad78',
      description : 'deneme',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
  {
      name : 'İş İlanları',
      to : 'IlanPageTwo',
      icon : 'engineering',
      description : 'deneme',
      bg : '#94d490',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
  {
      name : 'Yardımcı Arayanlar',
      to : 'IlanPageTwo',
      icon : 'child-friendly',
      description : 'deneme',
      bg : '#fe7a18',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
  {
      name : 'Hayvanlar Alemi',
      to : 'IlanPageTwo',
      icon : 'pets',
      description : 'deneme',
      bg : '#1db9e1',
      altCate : [
          {name : 'Konut',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'},
                  {name : 'Yazlık'},
                  {name : 'Kooperatif'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Çiftlik Evi'},
                  {name : 'Köşk & Konak'},
                  {name : 'Yalı'},
                  {name : 'Yalı Dairesi'}
              ]
              },
              {name : 'Turizm Amaçlı Kiralık',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Rezidans'},
                  {name : 'Müstakil Ev'},
                  {name : 'Villa'},
                  {name : 'Devre Mülk'},
                  {name : 'Apart & Pansiyon'}
              ]
              },
              {name : 'Devren Satılık Konut',
              altCate : [
                  {name : 'Daire'},
                  {name : 'Villa'}
              ]
              }
          ]
          },
          {name : 'İş yeri',
          altCate : [
              {name : 'Satılık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]
              },
              {name : 'Kiralık',
              altCate : [
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Atölye'},
                  {name : 'AVM'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe & Bar'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Enerji Santrali'},
                  {name : 'Fabrika'},
                  {name : 'Garaj & Park Yeri'},
                  {name : 'İmalathane'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Komple Bina'},
                  {name : 'Madem Ocağı'},
                  {name : 'Otopark'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Satılık',
              altCate : [
                  {name : 'Acente'},
                  {name : 'Akaryakıt İstasyonu'},
                  {name : 'Aktar & Baharatçı'},
                  {name : 'Anaokulu & Kreş'},
                  {name : 'Apartman Dairesi'},
                  {name : 'Araç Showroom & Servis'},
                  {name : 'Atölye'},
                  {name : 'AVM Standı'},
                  {name : 'Balıkçı'},
                  {name : 'Bar'},
                  {name : 'Bijuteri'},
                  {name : 'Börekçi'},
                  {name : 'Büfe'},
                  {name : 'Büro & Ofis'},
                  {name : 'Cafe'},
                  {name : 'CD & DVD Dükkanı'},
                  {name : 'Cep Telefonu Dükkanı'},
                  {name : 'Çamaşırhane'},
                  {name : 'Çay Ocağı'},
                  {name : 'Çiçekçi & Fidanlık'},
                  {name : 'Çiftlik'},
                  {name : 'Depo & Antrepo'},
                  {name : 'Düğün Salonu'},
                  {name : 'Dükkan & Mağaza'},
                  {name : 'Eczane & Medikal'},
                  {name : 'Elektrikçi & Hırdavatçı'},
                  {name : 'Elektronik Mağazası'},
                  {name : 'Etkinlik & Performans Salonu'},
                  {name : 'Fabrika & Ürem Tesisi'},
                  {name : 'Fatura Merkezi'},
                  {name : 'Fotoğraf Stüdyosu'},
                  {name : 'Gece Kulübü & Disko'},
                  {name : 'Giyim Mağazası'},
                  {name : 'Gözlükçü'},
                  {name : 'Halı Yıkama'},
                  {name : 'Huzur Evi'},
                  {name : 'İmalathane'},
                  {name : 'İnternet & Oyun Cafe'},
                  {name : 'İş Hanı'},
                  {name : 'İş Hanı Katı & Ofisi'},
                  {name : 'Kantin'},
                  {name : 'Kasap'},
                  {name : 'Kır & Kahvaltı Bahçesi'},
                  {name : 'Kıraathane'},
                  {name : 'Kırtasiye'},
                  {name : 'Kozmetik Mağazası'},
                  {name : 'Kuaför & Güzellik Merkezi'},
                  {name : 'Kurs & Eğitim Merkezi'},
                  {name : 'Kuru Temizleme'},
                  {name : 'Kuruyemişçi'},
                  {name : 'Kuyumcu'},
                  {name : 'Lunapark'},
                  {name : 'Maden Ocağı'},
                  {name : 'Manav'},
                  {name : 'Market'},
                  {name : 'Matbaa'},
                  {name : 'Modaevi'},
                  {name : 'Muayenehane'},
                  {name : 'Nakliyat & Kargo'},
                  {name : 'Nalbur'},
                  {name : 'Okul'},
                  {name : 'Otopark / Garaj'},
                  {name : 'Oto Servis & Bakım'},
                  {name : 'Pastane & Fırın'},
                  {name : 'Pazar Yeri'},
                  {name : 'Plaza'},
                  {name : 'Plaza Katı'},
                  {name : 'Radyo İstasyonu'},
                  {name : 'Restoran & Lokanta'},
                  {name : 'Rezidans Katı & Ofisi'},
                  {name : 'Sağlık Merkezi'},
                  {name : 'Sinema & Konferans Salonu'},
                  {name : 'SPA, Hamam & Sauna'},
                  {name : 'Spor Tesisi'},
                  {name : 'Villa'},
                  {name : 'Yurt'}
              ]},
              {name : 'Devren Kiralık'}
          ]
          },
          {name : 'Arsa',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]
          },
          {name : 'Bina',
          altCate: [
              {name : 'Satılık'},
              {name : 'Kiralık'}
          ]},
          {name : 'Devre Mülk',
          altCate: [
              {name : 'Akdeniz Bölgesi'},
              {name : 'Doğu Anadolu Bölgesi'},
              {name : 'Ege Bölgesi'},
              {name : 'Güneydoğu Anadolu Bölgesi'},
              {name : 'İç Anadolu Bölgesi'},
              {name : 'Karadeniz Bölgesi'},
              {name : 'Marmara Bölgesi'},
              {name : 'Kıbrıs'},
              {name : 'Yurtdışı'},
          ]},
          {name : 'Turistik Tesis'},
      ]
  },
]
const special = [
  {
    icon : 'priority-high',
    name : 'Acil Acil',
    altCategories : [],
    description : 'deneme',
    bg : '#babec1'
  },
  {
    icon : 'access-time',
    name : 'Son 48 Saat',
    altCategories : [],
    description : 'deneme',
    bg : '#babec1'
  },
]

const ilanlar = [
  {
    title : 'accent era 2011',
    img : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrCnBso5wkqumd5qHsqBqCTja_WfyG34WH9w&s',
    price : 470000
  },
  {
    title : 'accent era 2011',
    img : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrCnBso5wkqumd5qHsqBqCTja_WfyG34WH9w&s',
    price : 470000
  },
  {
    title : 'accent era 2011',
    img : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrCnBso5wkqumd5qHsqBqCTja_WfyG34WH9w&s',
    price : 470000
  },
]

export default function Search({navigation}) {
  const { pressed, setPressed } = useContext(StoreContext)
  useEffect(() => {
    const unsubscribe = navigation.addListener('focus', () => {
        setPressed(false)
    });
    return unsubscribe;
}, [navigation]);
  return (
    <ScrollView style={[styles.container]}>
      <SearchBar title='Kelime veya ilan No. ile ara' />
      <View style={[styles.containerCate, pressed && {display : 'none'}]}>
        <Categories categories={categories} searchMenu={true} iconSize={16} />
      </View>
      <View style={[styles.specialCate, pressed && {display : 'none'}]}>
        <Categories categories={special} searchMenu={true} iconSize={16} />
      </View>
      <Text style={[styles.titleIlanlar,  pressed && {display : 'none'} ]}>İLGELENEBİLECEĞİNİZ İLANLAR</Text>
      <Ilanlar ilanlar={ilanlar} navigate={'yönlendirilecek sayfa'} />
      <Text style={[styles.titleIlanlar,  pressed && {display : 'none'} ]}>YAKININIZDAKİ SAHİBİNDEN ALIŞVERİŞ İLANLARI</Text>
      <Ilanlar ilanlar={ilanlar} navigate={'yönlendirilecek sayfa'} />
      <Text style={[styles.titleIlanlar,  pressed && {display : 'none'} ]}>SON ARAMANIZA UYGUN İLANLAR</Text>
      <Ilanlar ilanlar={ilanlar} navigate={'yönlendirilecek sayfa'} />
      <Text style={[styles.titleIlanlar,  pressed && {display : 'none'} ]}>SON GEZDİĞİNİZ İLANLAR</Text>
      <Ilanlar ilanlar={ilanlar} navigate={'yönlendirilecek sayfa'} />
    </ScrollView>
  )
}

const styles = StyleSheet.create({
  container : { 
      backgroundColor : '#f2f2f2',
  },
  containerCate : {
    marginBottom : 50
  },
  titleIlanlar: {
    marginTop : 15,
    marginLeft: 15,
    color : '#9a9a9a'
  },


})